"use client"

import React, { useState, useRef, useEffect, useCallback } from "react"
import { Button } from "@/components/ui/button"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Send,
  Sparkles,
  Upload,
  Eye,
  Code,
  Smartphone,
  Monitor,
  Tablet,
  Undo,
  Redo,
  Download,
  Share,
  Settings,
  Layers,
  Type,
  Image,
  Square,
  Layout,
  Palette,
  ChevronRight,
  Trash2,
  Copy,
  MoveUp,
  MoveDown,
  X,
  Plus,
  GripVertical,
  Home,
  Package,
  Users,
  Mail,
  ArrowUp,
  Loader2,
  Check,
  RefreshCw,
  Wand2,
  MessageSquare,
  PanelLeftClose,
  PanelLeftOpen,
  Globe,
  MousePointer2,
} from "lucide-react"
import { PublishDialog } from "./publish-dialog"
import { DeploymentSuccessView } from "./deployment-success-view"
import { PageManager } from "./page-manager"
import { BlockContextMenu } from "./block-context-menu"
import { AIRegeneratePanel } from "./ai-regenerate-panel"
import { SortableBlocks, Block } from "./block-editor/sortable-blocks"
import { PagePreview } from "./page-preview"
import { SelectElementProvider } from "./select-element-provider"
import { VisualSelectOverlay, type ElementChanges } from "./visual-select-overlay"
import type { DetectedElement } from "@/lib/element-detector"
import { getElementDescription } from "@/lib/css-selector-generator"
import { AIStyleSelectProvider } from "./ai-style-select-provider"
import { useElementStyleStore } from "@/lib/element-style-store"

// Types
type ViewMode = "desktop" | "tablet" | "mobile"
type EditorTab = "chat" | "layers" | "components"

interface ChatMessage {
  id: string
  role: "user" | "assistant"
  content: string
  timestamp: Date
}

interface PageBlock {
  id: string
  type: "hero" | "features" | "products" | "cta" | "text" | "image" | "button"
  content: Record<string, unknown>
  selected?: boolean
}

// Main Visual Editor Component
interface VisualEditorProps {
  initialPrompt?: string
}

export function VisualEditor({ initialPrompt }: VisualEditorProps = {}) {
  // State
  const [isGenerating, setIsGenerating] = useState(false)
  const [generationProgress, setGenerationProgress] = useState(0)
  const [generationStep, setGenerationStep] = useState("")
  const [hasGenerated, setHasGenerated] = useState(false)
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([])
  const [inputValue, setInputValue] = useState(initialPrompt || "")
  const hasAutoGeneratedRef = useRef(false)
  const [viewMode, setViewMode] = useState<ViewMode>("desktop")
  const [leftPanelOpen, setLeftPanelOpen] = useState(true)
  const [leftTab, setLeftTab] = useState<EditorTab>("chat")
  
  // AI Style Store - 用于元素选择和样式修改
  const { 
    selectedId: aiSelectedId, 
    setSelectedId: setAISelectedId,
    isSelectMode,
    setSelectMode: setAISelectMode,
    updateTailwindClasses,
    overrides: aiOverrides,
    clearAllOverrides,
  } = useElementStyleStore()
  const [selectedBlock, setSelectedBlock] = useState<string | null>(null)
  const [activePage, setActivePage] = useState("home")
  const [isEditing, setIsEditing] = useState(true)
  const [isPublishing, setIsPublishing] = useState(false)
  const [publishStep, setPublishStep] = useState(0)
  const [publishStatus, setPublishStatus] = useState<"idle" | "queued" | "building" | "deploying" | "success" | "failed">("idle")
  const [publishUrl, setPublishUrl] = useState<string | null>(null)
  const [showPublishDialog, setShowPublishDialog] = useState(false)
  const [publishType, setPublishType] = useState<"standard" | "custom">("standard")
  const [contextMenu, setContextMenu] = useState<{ x: number; y: number; blockId: string } | null>(null)
  const [showAIRegenerate, setShowAIRegenerate] = useState(false)
  const [regenerateBlockId, setRegenerateBlockId] = useState<string | null>(null)
  const [blocks, setBlocks] = useState<Block[]>([])
  const [selectElementEnabled, setSelectElementEnabled] = useState(false)
  const [freeDragEnabled, setFreeDragEnabled] = useState(false)
  const [selectedElementInfo, setSelectedElementInfo] = useState<{
    element: DetectedElement
    selector: string
    label: string
  } | null>(null)
  const [selectedElements, setSelectedElements] = useState<Array<{
    element: DetectedElement
    selector: string
    label: string
  }>>([])
  const previewContainerRef = useRef<HTMLDivElement>(null)
  const selectableAreaRef = useRef<HTMLDivElement>(null)
  
  const chatEndRef = useRef<HTMLDivElement>(null)
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  // Pages data
  const pages = [
    { id: "home", name: "Home", icon: Home },
    { id: "products", name: "Products", icon: Package },
    { id: "about", name: "About", icon: Users },
    { id: "contact", name: "Contact", icon: Mail },
  ]

  // Components library
  const componentLibrary = [
    { id: "hero", name: "Hero Section", icon: Layout },
    { id: "features", name: "Features Grid", icon: Layers },
    { id: "products", name: "Product Cards", icon: Package },
    { id: "cta", name: "Call to Action", icon: Square },
    { id: "text", name: "Text Block", icon: Type },
    { id: "image", name: "Image", icon: Image },
    { id: "button", name: "Button", icon: Square },
  ]

  // Auto scroll chat to bottom
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" })
  }, [chatMessages])

  // Simulate generation process (internal function that accepts prompt)
  const startGenerationWithPrompt = useCallback(async (prompt: string) => {
    if (!prompt.trim()) return

    // 生成新网站前清空旧的样式覆盖（避免把上一次的“红色按钮”等状态带进来）
    clearAllOverrides()
    setAISelectedId(null)
    
    // Add user message
    const userMessage: ChatMessage = {
      id: Date.now().toString(),
      role: "user",
      content: prompt,
      timestamp: new Date(),
    }
    setChatMessages(prev => [...prev, userMessage])
    setIsGenerating(true)
    setGenerationProgress(0)

    // Simulate generation steps
    const steps = [
      { progress: 10, step: "Analyzing your requirements..." },
      { progress: 25, step: "Selecting optimal template..." },
      { progress: 40, step: "Generating page structure..." },
      { progress: 60, step: "Creating content sections..." },
      { progress: 75, step: "Applying styles and design..." },
      { progress: 90, step: "Optimizing for SEO..." },
      { progress: 100, step: "Finalizing website..." },
    ]

    for (const step of steps) {
      await new Promise(resolve => setTimeout(resolve, 500))
      setGenerationProgress(step.progress)
      setGenerationStep(step.step)
    }

    // Add assistant response
    const assistantMessage: ChatMessage = {
      id: (Date.now() + 1).toString(),
      role: "assistant",
      content: "I've generated your website based on your requirements. The site includes a professional hero section, features showcase, product gallery, and contact form. You can click on any element in the preview to edit it, or ask me to make specific changes.",
      timestamp: new Date(),
    }
    setChatMessages(prev => [...prev, assistantMessage])
    
    setIsGenerating(false)
    setHasGenerated(true)
  }, [])

  // Auto-generate if initialPrompt is provided
  useEffect(() => {
    if (initialPrompt && initialPrompt.trim() && !hasAutoGeneratedRef.current && !isGenerating && !hasGenerated) {
      hasAutoGeneratedRef.current = true
      // Small delay to ensure component is fully mounted
      setTimeout(() => {
        startGenerationWithPrompt(initialPrompt.trim())
      }, 300)
    }
  }, [initialPrompt, isGenerating, hasGenerated, startGenerationWithPrompt])


  // Public function that uses current inputValue
  const startGeneration = async () => {
    if (!inputValue.trim()) return
    const prompt = inputValue.trim()
    setInputValue("") // Clear input after starting
    await startGenerationWithPrompt(prompt)
  }

  // One-click publish flow
  const publishSteps = [
    { label: "Queued", status: "queued" as const },
    { label: "Building static files", status: "building" as const },
    { label: "Deploying to CDN", status: "deploying" as const },
    { label: "Completed", status: "success" as const },
  ]

  // Open publish dialog
  const handlePublishClick = () => {
    setShowPublishDialog(true)
  }

  // Publish to standard subdomain
  const startPublishStandard = async () => {
    setShowPublishDialog(false)
    setPublishType("standard")
    await startPublishFlow(false)
  }

  // Publish to custom domain
  const startPublishCustom = async () => {
    setShowPublishDialog(false)
    setPublishType("custom")
    // Navigate to custom domain page or show custom domain setup
    window.location.href = "/domains"
  }

  // Main publish flow
  const startPublishFlow = async (isCustomDomain = false) => {
    if (isPublishing) return
    setIsPublishing(true)
    setPublishStatus("queued")
    setPublishStep(0)
    setPublishUrl(null)

    try {
      const res = await fetch("/api/publish", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ 
          projectId: "leadsite",
          publishType: isCustomDomain ? "custom" : "standard",
        }),
      })
      const data = await res.json()
      if (data.success && data.subdomain) {
        setPublishUrl(`https://${data.subdomain}`)
      } else {
        throw new Error("Publish failed")
      }
    } catch (e) {
      console.error(e)
      setPublishStatus("failed")
      setIsPublishing(false)
      return
    }

    // Simulate step progression
    publishSteps.forEach((step, idx) => {
      setTimeout(() => {
        setPublishStep(idx)
        setPublishStatus(step.status)
        if (step.status === "success") {
          setIsPublishing(false)
        }
      }, idx * 700 + 300)
    })
  }

  // Handle AI regeneration request
  const handleRegenerate = async (instruction: string) => {
    const userMessage: ChatMessage = {
      id: Date.now().toString(),
      role: "user",
      content: instruction,
      timestamp: new Date(),
    }
    setChatMessages(prev => [...prev, userMessage])
    setInputValue("")
    setIsGenerating(true)
    setGenerationStep("Updating your website...")

    await new Promise(resolve => setTimeout(resolve, 2000))

    const assistantMessage: ChatMessage = {
      id: (Date.now() + 1).toString(),
      role: "assistant",
      content: `Done! I've updated the website based on your request: "${instruction}". The changes are now reflected in the preview.`,
      timestamp: new Date(),
    }
    setChatMessages(prev => [...prev, assistantMessage])
    setIsGenerating(false)
  }

  // Handle element modification with AI
  const handleElementModify = async (instruction: string) => {
    // 支持两种选中方式：selectedElementInfo（原有方式）或 aiSelectedId（Zustand Store 方式）
    const targetElementId = selectedElementInfo?.selector || aiSelectedId
    const targetLabel = selectedElementInfo?.label || aiSelectedId || "元素"
    
    if (!targetElementId) return

    const userMessage: ChatMessage = {
      id: Date.now().toString(),
      role: "user",
      content: `修改 "${targetLabel}": ${instruction}`,
      timestamp: new Date(),
    }
    setChatMessages(prev => [...prev, userMessage])
    setInputValue("")
    setIsGenerating(true)
    setGenerationStep("AI 正在分析修改指令...")

    try {
      // 调用新的 AI 样式 API，返回 Tailwind 类名
      const response = await fetch('/api/ai-style', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          instruction,
          elementId: targetElementId,
        }),
      })

      const data = await response.json()

      if (data.success && data.tailwindClasses) {
        console.log('[ElementModify] AI 返回 Tailwind 类名:', {
          elementId: targetElementId,
          tailwindClasses: data.tailwindClasses,
          description: data.description,
        })

        // 通过 Zustand Store 更新样式（React 状态驱动，不直接操作 DOM）
        updateTailwindClasses(targetElementId, data.tailwindClasses, instruction)

        // 同时也直接应用到 DOM 元素（确保即时生效）
        const targetElement = selectedElementInfo?.element?.element || 
          document.querySelector(`[data-element-id="${targetElementId}"]`) as HTMLElement
        
        if (targetElement) {
          // 保存原始类名
          if (!targetElement.hasAttribute('data-original-class')) {
            targetElement.setAttribute('data-original-class', targetElement.className)
          }
          // 添加新的 Tailwind 类名
          const originalClass = targetElement.getAttribute('data-original-class') || ''
          targetElement.className = `${originalClass} ${data.tailwindClasses}`.trim()
          console.log('[ElementModify] 已应用类名到元素:', targetElement.className)
        }

        const assistantMessage: ChatMessage = {
          id: (Date.now() + 1).toString(),
          role: "assistant",
          content: `✅ 已完成！我已将 "${targetLabel}" ${data.description || '按照您的要求进行了修改'}。\n\n应用的样式: \`${data.tailwindClasses}\``,
          timestamp: new Date(),
        }
        setChatMessages(prev => [...prev, assistantMessage])
        
        // 清除选中的元素
        setSelectedElementInfo(null)
        setAISelectedId(null)
      } else {
        throw new Error(data.error || 'Failed to modify element')
      }
    } catch (error) {
      console.error('[ElementModify] 修改失败:', error)
      
      let errorMsg = `抱歉，修改元素时出现错误。`
      
      if (error instanceof Error) {
        errorMsg += `\n错误信息: ${error.message}`
      }
      
      const errorMessage: ChatMessage = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content: errorMsg,
        timestamp: new Date(),
      }
      setChatMessages(prev => [...prev, errorMessage])
    } finally {
      setIsGenerating(false)
    }
  }

  // Handle key press in input
  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault()
      if (selectedElementInfo || aiSelectedId) {
        // 如果有选中的元素，调用元素修改函数
        handleElementModify(inputValue)
      } else if (hasGenerated) {
        handleRegenerate(inputValue)
      } else {
        startGeneration()
      }
    }
  }

  // Get viewport width based on mode
  const getViewportWidth = () => {
    switch (viewMode) {
      case "mobile": return "375px"
      case "tablet": return "768px"
      default: return "100%"
    }
  }

  return (
    <div className="h-screen flex flex-col bg-muted/30 overflow-hidden" suppressHydrationWarning>
      {/* Top Toolbar */}
      <header className="h-14 border-b border-border bg-background flex items-center justify-between px-4 shrink-0">
        <div className="flex items-center gap-4">
          {/* Logo */}
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-foreground rounded-lg flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-background" />
            </div>
            <span className="font-semibold">LeadSite AI</span>
          </div>

          {/* Toggle Left Panel */}
          <Button
            variant="ghost"
            size="icon"
            onClick={() => setLeftPanelOpen(!leftPanelOpen)}
            className="h-8 w-8"
          >
            {leftPanelOpen ? <PanelLeftClose className="w-4 h-4" /> : <PanelLeftOpen className="w-4 h-4" />}
          </Button>

          {/* Undo/Redo */}
          <div className="flex items-center gap-1 border-l border-border pl-4">
            <Button variant="ghost" size="icon" className="h-8 w-8">
              <Undo className="w-4 h-4" />
            </Button>
            <Button variant="ghost" size="icon" className="h-8 w-8">
              <Redo className="w-4 h-4" />
            </Button>
          </div>

          {/* Free Drag Toggle */}
          <div className="flex items-center gap-1 border-l border-border pl-4">
            <Button
              variant={freeDragEnabled ? "secondary" : "ghost"}
              size="sm"
              className={`h-8 gap-2 ${freeDragEnabled ? 'bg-purple-100 dark:bg-purple-900 text-purple-700 dark:text-purple-300 border border-purple-300 dark:border-purple-700' : ''}`}
              onClick={() => {
                setFreeDragEnabled(!freeDragEnabled)
                if (!freeDragEnabled) setSelectElementEnabled(false)
              }}
              title="Free Drag (自由拖拽移动元素)"
            >
              <GripVertical className="w-4 h-4" />
              <span className="text-xs font-medium">Free Drag</span>
            </Button>
          </div>
        </div>

        {/* Center - Viewport Controls */}
        <div className="flex items-center gap-1 bg-muted rounded-lg p-1">
          <Button
            variant={viewMode === "desktop" ? "secondary" : "ghost"}
            size="sm"
            onClick={() => setViewMode("desktop")}
            className="h-7 px-3"
          >
            <Monitor className="w-4 h-4" />
          </Button>
          <Button
            variant={viewMode === "tablet" ? "secondary" : "ghost"}
            size="sm"
            onClick={() => setViewMode("tablet")}
            className="h-7 px-3"
          >
            <Tablet className="w-4 h-4" />
          </Button>
          <Button
            variant={viewMode === "mobile" ? "secondary" : "ghost"}
            size="sm"
            onClick={() => setViewMode("mobile")}
            className="h-7 px-3"
          >
            <Smartphone className="w-4 h-4" />
          </Button>
        </div>

        {/* Right Actions */}
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm" className="gap-2">
            <Eye className="w-4 h-4" />
            Preview
          </Button>
          <Button variant="ghost" size="sm" className="gap-2">
            <Code className="w-4 h-4" />
            Code
          </Button>
          <div className="h-6 w-px bg-border mx-2" />
          <Button variant="ghost" size="icon" className="h-8 w-8">
            <Download className="w-4 h-4" />
          </Button>
          <div className="relative">
            <Select
              onValueChange={(value) => {
                if (value === "export-pdf") {
                  // Export as PDF
                  console.log("Export as PDF")
                } else if (value === "export-html") {
                  // Export as HTML
                  console.log("Export as HTML")
                } else if (value === "share-link") {
                  // Share link
                  console.log("Share link")
                } else if (value === "embed") {
                  // Embed code
                  console.log("Get embed code")
                }
              }}
            >
              <SelectTrigger className="h-8 w-8 p-0 border-0 bg-transparent hover:bg-accent [&>svg]:hidden">
                <span className="sr-only">Share options</span>
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="export-pdf">Export as PDF</SelectItem>
                <SelectItem value="export-html">Export as HTML</SelectItem>
                <SelectItem value="share-link">Share Link</SelectItem>
                <SelectItem value="embed">Embed Code</SelectItem>
              </SelectContent>
            </Select>
            <div className="absolute inset-0 pointer-events-none flex items-center justify-center">
              <Share className="w-4 h-4" />
            </div>
          </div>
          <Button size="sm" className="gap-2 ml-2" onClick={handlePublishClick} disabled={isPublishing || !hasGenerated}>
            <Globe className="w-4 h-4" />
            {isPublishing ? "Publishing..." : "Publish"}
          </Button>
        </div>
      </header>

      {/* Main Content Area */}
      <div className="flex-1 flex overflow-hidden">
        {/* Left Panel - AI Chat / Layers */}
        {leftPanelOpen && (
          <aside className="w-80 border-r border-border bg-background flex flex-col shrink-0">
            {/* Tabs */}
            <div className="flex border-b border-border">
              <button
                onClick={() => setLeftTab("chat")}
                className={`flex-1 px-4 py-3 text-sm font-medium transition-colors ${
                  leftTab === "chat"
                    ? "text-foreground border-b-2 border-foreground"
                    : "text-muted-foreground hover:text-foreground"
                }`}
              >
                <MessageSquare className="w-4 h-4 inline mr-2" />
                AI Chat
              </button>
              <button
                onClick={() => setLeftTab("layers")}
                className={`flex-1 px-4 py-3 text-sm font-medium transition-colors ${
                  leftTab === "layers"
                    ? "text-foreground border-b-2 border-foreground"
                    : "text-muted-foreground hover:text-foreground"
                }`}
              >
                <Layers className="w-4 h-4 inline mr-2" />
                Pages
              </button>
              <button
                onClick={() => setLeftTab("components")}
                className={`flex-1 px-4 py-3 text-sm font-medium transition-colors ${
                  leftTab === "components"
                    ? "text-foreground border-b-2 border-foreground"
                    : "text-muted-foreground hover:text-foreground"
                }`}
              >
                <Plus className="w-4 h-4 inline mr-2" />
                Add
              </button>
            </div>

            {/* Tab Content */}
            <div className="flex-1 flex flex-col overflow-hidden">
              {leftTab === "chat" && (
                <>
                  {/* Chat Messages */}
                  <div className="flex-1 overflow-y-auto p-4 space-y-4">
                    {chatMessages.length === 0 && !isGenerating && (
                      <div className="text-center py-8">
                        <div className="w-12 h-12 bg-muted rounded-full flex items-center justify-center mx-auto mb-4">
                          <Sparkles className="w-6 h-6 text-muted-foreground" />
                        </div>
                        <h3 className="font-medium mb-2">Start Building</h3>
                        <p className="text-sm text-muted-foreground">
                          Describe what you want to build or upload your content to get started.
                        </p>
                      </div>
                    )}

                    {chatMessages.map((message) => (
                      <div
                        key={message.id}
                        className={`flex gap-3 ${message.role === "user" ? "flex-row-reverse" : ""}`}
                      >
                        <div
                          className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 ${
                            message.role === "user" ? "bg-foreground" : "bg-muted"
                          }`}
                        >
                          {message.role === "user" ? (
                            <span className="text-xs text-background font-medium">You</span>
                          ) : (
                            <Sparkles className="w-4 h-4 text-muted-foreground" />
                          )}
                        </div>
                        <div
                          className={`max-w-[85%] p-3 rounded-2xl text-sm ${
                            message.role === "user"
                              ? "bg-foreground text-background"
                              : "bg-muted"
                          }`}
                        >
                          {message.content}
                        </div>
                      </div>
                    ))}

                    {/* Generation Progress */}
                    {isGenerating && (
                      <div className="flex gap-3">
                        <div className="w-8 h-8 rounded-full bg-muted flex items-center justify-center shrink-0">
                          <Loader2 className="w-4 h-4 animate-spin text-muted-foreground" />
                        </div>
                        <div className="flex-1">
                          <div className="bg-muted rounded-2xl p-3">
                            <div className="flex items-center gap-2 mb-2">
                              <span className="text-sm font-medium">{generationStep}</span>
                            </div>
                            <div className="h-1.5 bg-background rounded-full overflow-hidden">
                              <div
                                className="h-full bg-foreground transition-all duration-300"
                                style={{ width: `${generationProgress}%` }}
                              />
                            </div>
                          </div>
                        </div>
                      </div>
                    )}

                    <div ref={chatEndRef} />
                  </div>

                  {/* Input Area */}
                  <div className="p-4 border-t border-border">
                    {/* Selected Element Tag - 类似 Cursor 的元素标签显示 */}
                    {(selectedElementInfo || aiSelectedId) && (
                      <div className="mb-2 flex items-center gap-2 flex-wrap">
                        <div className="inline-flex items-center gap-1.5 px-2 py-1 bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300 rounded-md text-xs font-medium border border-blue-200 dark:border-blue-800">
                          <MousePointer2 className="w-3 h-3" />
                          <span className="max-w-[180px] truncate">
                            {selectedElementInfo?.label || aiSelectedId}
                          </span>
                          <button
                            onClick={() => {
                              setSelectedElementInfo(null)
                              setAISelectedId(null)
                            }}
                            className="ml-0.5 hover:bg-blue-200 dark:hover:bg-blue-800 rounded p-0.5 transition-colors"
                          >
                            <X className="w-3 h-3" />
                          </button>
                        </div>
                        <span className="text-xs text-muted-foreground">已选中元素，输入指令修改样式</span>
                      </div>
                    )}
                    <div className="relative bg-muted rounded-xl">
                      <textarea
                        ref={textareaRef}
                        value={inputValue}
                        onChange={(e) => setInputValue(e.target.value)}
                        onKeyDown={handleKeyPress}
                        placeholder={
                          (selectedElementInfo || aiSelectedId)
                            ? `描述如何修改 "${selectedElementInfo?.label || aiSelectedId}"...`
                            : hasGenerated
                              ? "Ask AI to make changes..."
                              : "Describe your website or paste content..."
                        }
                        rows={1}
                        className="w-full px-4 py-3 pr-24 bg-transparent rounded-xl resize-none focus:outline-none text-sm min-h-[48px] max-h-[120px]"
                        style={{ height: "auto" }}
                        onInput={(e) => {
                          const target = e.target as HTMLTextAreaElement
                          target.style.height = "auto"
                          target.style.height = `${Math.min(target.scrollHeight, 120)}px`
                        }}
                      />
                      <div className="absolute right-2 bottom-2 flex items-center gap-1">
                        <Button variant="ghost" size="icon" className="h-8 w-8">
                          <Upload className="w-4 h-4" />
                        </Button>
                        <Button
                          variant={selectElementEnabled || isSelectMode ? "default" : "ghost"}
                          size="icon"
                          className={`h-8 w-8 ${(selectElementEnabled || isSelectMode) ? 'bg-blue-500 text-white hover:bg-blue-600' : ''}`}
                          onClick={() => {
                            const newState = !selectElementEnabled
                            setSelectElementEnabled(newState)
                            setAISelectMode(newState) // 同时启用 AI 样式选择模式
                            if (newState) {
                              setFreeDragEnabled(false)
                            } else {
                              // 如果关闭选择模式，清除所有选中状态
                              setSelectedElementInfo(null)
                              setSelectedElements([])
                            }
                          }}
                          title="Select Element (页面元素选择功能)"
                        >
                          <MousePointer2 className="w-4 h-4" />
                        </Button>
                        <Button
                          size="icon"
                          className="h-8 w-8"
                          onClick={() => {
                            if (selectedElementInfo || aiSelectedId) {
                              handleElementModify(inputValue)
                            } else if (hasGenerated) {
                              handleRegenerate(inputValue)
                            } else {
                              startGeneration()
                            }
                          }}
                          disabled={!inputValue.trim() || isGenerating}
                        >
                          <ArrowUp className="w-4 h-4" />
                        </Button>
                      </div>
                    </div>
                  </div>
                </>
              )}

              {leftTab === "layers" && (
                <PageManager
                  pages={pages}
                  activePage={activePage}
                  onPageChange={setActivePage}
                  onPageReorder={(newPages) => {
                    // Handle page reorder if needed
                    console.log("Pages reordered:", newPages)
                  }}
                  onAddPage={() => {
                    // Handle add page
                    console.log("Add new page")
                  }}
                />
              )}

              {leftTab === "components" && (
                <div className="flex-1 p-4 overflow-y-auto">
                  <h4 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3">
                    Drag to add
                  </h4>
                  <div className="grid grid-cols-2 gap-2">
                    {componentLibrary.map((comp) => (
                      <button
                        key={comp.id}
                        className="flex flex-col items-center gap-2 p-4 rounded-lg border border-border hover:border-foreground hover:bg-muted/50 transition-colors cursor-grab"
                        draggable
                      >
                        <comp.icon className="w-5 h-5 text-muted-foreground" />
                        <span className="text-xs">{comp.name}</span>
                      </button>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </aside>
        )}

        {/* Center - Preview Area */}
        <main className="flex-1 overflow-hidden flex flex-col bg-muted/50">
          {/* Preview Container */}
          <div ref={selectableAreaRef} className="flex-1 overflow-auto p-4 flex items-start justify-center">
            <AIStyleSelectProvider containerRef={previewContainerRef as React.RefObject<HTMLElement>}>
              <div
                className="bg-background rounded-lg shadow-lg overflow-hidden transition-all duration-300 h-full"
                style={{
                  width: getViewportWidth(),
                  maxWidth: "100%",
                }}
              >
                {!hasGenerated && !isGenerating ? (
                /* Empty State */
                <div className="h-full flex items-center justify-center p-8">
                  <div className="text-center max-w-md">
                    <div className="w-16 h-16 bg-muted rounded-2xl flex items-center justify-center mx-auto mb-6">
                      <Wand2 className="w-8 h-8 text-muted-foreground" />
                    </div>
                    <h2 className="text-2xl font-semibold mb-3">Create Your Website</h2>
                    <p className="text-muted-foreground mb-6">
                      Describe what you want to build in the chat panel, or upload your existing content (PDF, PPT, URL) to get started.
                    </p>
                    <div className="flex flex-wrap gap-2 justify-center">
                      <Button variant="outline" size="sm" onClick={() => setInputValue("Create a professional B2B industrial machinery website")}>
                        B2B Industrial
                      </Button>
                      <Button variant="outline" size="sm" onClick={() => setInputValue("Create a modern SaaS landing page")}>
                        SaaS Landing
                      </Button>
                      <Button variant="outline" size="sm" onClick={() => setInputValue("Create an e-commerce product showcase")}>
                        E-commerce
                      </Button>
                    </div>
                  </div>
                </div>
              ) : (
                /* Generated Website Preview */
                <SelectElementProvider 
                  enabled={selectElementEnabled}
                  containerRef={selectableAreaRef as React.RefObject<HTMLElement>}
                  onElementSelect={(element, selector) => {
                    if (element && selector) {
                      const label = getElementDescription(element.element)
                      console.log('[SelectElement] 元素已选中:', {
                        element: element.element,
                        tagName: element.element.tagName,
                        className: element.element.className,
                        selector,
                        label,
                      })
                      
                      const newSelectedElement = {
                        element,
                        selector,
                        label,
                      }
                      
                      // 支持多选：检查是否已选中，如果已选中则移除，否则添加
                      setSelectedElements(prev => {
                        const existingIndex = prev.findIndex(
                          item => item.selector === selector
                        )
                        if (existingIndex >= 0) {
                          // 如果已选中，则移除
                          return prev.filter((_, index) => index !== existingIndex)
                        } else {
                          // 如果未选中，则添加
                          return [...prev, newSelectedElement]
                        }
                      })
                      
                      // 同时更新单个选中信息（用于兼容现有逻辑）
                      setSelectedElementInfo(newSelectedElement)
                    }
                  }}
                >
                  <div ref={previewContainerRef} className="h-full overflow-auto relative">
                    {blocks.length > 0 && isEditing ? (
                      <div onClick={() => setSelectedBlock(null)}>
                        <SortableBlocks
                          blocks={blocks}
                          isEditing={isEditing}
                          selectedBlockId={selectedBlock}
                          onBlockSelect={setSelectedBlock}
                          onBlockReorder={setBlocks}
                          onBlockContextMenu={(blockId, e) => {
                            e.stopPropagation()
                            setContextMenu({ x: e.clientX, y: e.clientY, blockId })
                          }}
                          className="space-y-0"
                        />
                      </div>
                    ) : (
                      <PagePreview page={activePage as "home" | "products" | "about" | "contact"} isEditing={isEditing} selectElementEnabled={selectElementEnabled} />
                    )}
                    
                    {/* Free Drag Overlay - 类似 Cursor 的可视化编辑 */}
                    {freeDragEnabled && (
                      <VisualSelectOverlay
                        enabled={freeDragEnabled}
                        containerRef={previewContainerRef as React.RefObject<HTMLElement>}
                        onElementSelect={(element, selector) => {
                          if (element) {
                            console.log('[FreeDrag] Selected:', { 
                              element, 
                              selector,
                              tagName: element.element.tagName,
                              className: element.element.className 
                            })
                          } else {
                            console.log('[FreeDrag] Selection cleared')
                          }
                        }}
                        onElementUpdate={(element, changes) => {
                          if (element) {
                            console.log('[FreeDrag] Updated:', { 
                              element: element.tagName, 
                              className: element.className,
                              changes 
                            })
                            
                            // 永久保存样式更改
                            if (changes.styles) {
                              Object.entries(changes.styles).forEach(([key, value]) => {
                                element.style.setProperty(key, value)
                              })
                              console.log('[FreeDrag] Styles applied permanently')
                            }
                            
                            // 这里可以进一步保存到数据库或生成新的代码
                            // 例如：saveElementPosition(element.dataset.id, changes)
                          }
                        }}
                        onElementDelete={(element) => {
                          if (element) {
                            console.log('[FreeDrag] Delete:', element)
                            if (confirm('确定要删除这个元素吗？')) {
                              element.remove()
                            }
                          }
                        }}
                        onElementDuplicate={(element) => {
                          if (element) {
                            console.log('[FreeDrag] Duplicate:', element)
                            const clone = element.cloneNode(true) as HTMLElement
                            clone.style.position = 'relative'
                            clone.style.marginTop = '10px'
                            element.parentNode?.insertBefore(clone, element.nextSibling)
                          }
                        }}
                      />
                    )}
                  </div>
                </SelectElementProvider>
              )}
              </div>
            </AIStyleSelectProvider>
          </div>
        </main>

      </div>

      {/* Publish Dialog */}
      {/* Context Menu */}
      {contextMenu && (
        <BlockContextMenu
          x={contextMenu.x}
          y={contextMenu.y}
          onClose={() => setContextMenu(null)}
          onEdit={() => {
            setSelectedBlock(contextMenu.blockId)
            setContextMenu(null)
          }}
          onViewLayout={() => {
            // Toggle layout view mode
            console.log("View layout for block:", contextMenu.blockId)
            setContextMenu(null)
          }}
          onDuplicate={() => {
            const block = blocks.find((b) => b.id === contextMenu.blockId)
            if (block) {
              const newBlock: Block = {
                id: `block-${Date.now()}`,
                type: block.type,
                content: block.content,
              }
              const index = blocks.findIndex((b) => b.id === contextMenu.blockId)
              const newBlocks = [...blocks]
              newBlocks.splice(index + 1, 0, newBlock)
              setBlocks(newBlocks)
            }
            setContextMenu(null)
          }}
          onFavorite={() => {
            // Toggle favorite status (can be stored in block metadata)
            console.log("Favorite block:", contextMenu.blockId)
            setContextMenu(null)
          }}
          onDelete={() => {
            setBlocks(blocks.filter((b) => b.id !== contextMenu.blockId))
            setSelectedBlock(null)
            setContextMenu(null)
          }}
          onMoveUp={() => {
            const index = blocks.findIndex((b) => b.id === contextMenu.blockId)
            if (index > 0) {
              const newBlocks = [...blocks]
              ;[newBlocks[index - 1], newBlocks[index]] = [newBlocks[index], newBlocks[index - 1]]
              setBlocks(newBlocks)
            }
            setContextMenu(null)
          }}
          onMoveDown={() => {
            const index = blocks.findIndex((b) => b.id === contextMenu.blockId)
            if (index < blocks.length - 1) {
              const newBlocks = [...blocks]
              ;[newBlocks[index], newBlocks[index + 1]] = [newBlocks[index + 1], newBlocks[index]]
              setBlocks(newBlocks)
            }
            setContextMenu(null)
          }}
          onAIRewrite={() => {
            setRegenerateBlockId(contextMenu.blockId)
            setShowAIRegenerate(true)
            setContextMenu(null)
          }}
          onInsertAbove={(type) => {
            const index = blocks.findIndex((b) => b.id === contextMenu.blockId)
            const newBlock: Block = { id: `block-${Date.now()}`, type, content: null }
            const newBlocks = [...blocks]
            newBlocks.splice(index, 0, newBlock)
            setBlocks(newBlocks)
            setContextMenu(null)
          }}
          onInsertBelow={(type) => {
            const index = blocks.findIndex((b) => b.id === contextMenu.blockId)
            const newBlock: Block = { id: `block-${Date.now()}`, type, content: null }
            const newBlocks = [...blocks]
            newBlocks.splice(index + 1, 0, newBlock)
            setBlocks(newBlocks)
            setContextMenu(null)
          }}
        />
      )}

      {/* AI Regenerate Panel */}
      <AIRegeneratePanel
        open={showAIRegenerate}
        blockId={regenerateBlockId || undefined}
        blockContent="Sample content to be regenerated"
        onClose={() => {
          setShowAIRegenerate(false)
          setRegenerateBlockId(null)
        }}
        onRegenerate={async (instruction) => {
          await new Promise((resolve) => setTimeout(resolve, 1500))
          console.log("Regenerating block:", regenerateBlockId, "with instruction:", instruction)
        }}
      />

      <PublishDialog
        open={showPublishDialog}
        onClose={() => setShowPublishDialog(false)}
        onPublishStandard={startPublishStandard}
        onPublishCustom={startPublishCustom}
        projectName="leadsite"
      />

      {/* Publish Success View */}
      {publishStatus === "success" && publishUrl && (
        <DeploymentSuccessView
          subdomain={publishUrl.replace("https://", "")}
          projectId="leadsite"
          onClose={() => {
            setIsPublishing(false)
            setPublishStatus("idle")
            setPublishStep(0)
            setPublishUrl(null)
          }}
        />
      )}

      {/* Publish Progress Modal */}
      {isPublishing && (
        <div className="fixed inset-0 z-[60] bg-black/40 backdrop-blur-sm flex items-center justify-center p-4">
          <div className="w-full max-w-md bg-background rounded-2xl shadow-2xl border border-border p-5 space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-lg font-semibold">Publishing Site</h3>
                <p className="text-sm text-muted-foreground">One-click deploy to leadsite.ai</p>
              </div>
              {publishStatus === "success" && (
                <span className="inline-flex items-center gap-1 text-sm text-emerald-600">
                  <Check className="w-4 h-4" />
                  Success
                </span>
              )}
              {publishStatus === "failed" && (
                <span className="inline-flex items-center gap-1 text-sm text-destructive">
                  <X className="w-4 h-4" />
                  Failed
                </span>
              )}
            </div>

            <div className="space-y-3">
              {publishSteps.map((step, idx) => {
                const active = idx === publishStep
                const done = idx < publishStep || publishStatus === "success"
                const failed = publishStatus === "failed"
                return (
                  <div key={step.label} className="flex items-center gap-3">
                    <div
                      className={`w-9 h-9 rounded-full border flex items-center justify-center ${
                        failed
                          ? "border-destructive text-destructive"
                          : done
                            ? "border-emerald-500 text-emerald-600"
                            : active
                              ? "border-foreground text-foreground"
                              : "border-border text-muted-foreground"
                      }`}
                    >
                      {done ? <Check className="w-4 h-4" /> : active ? <Loader2 className="w-4 h-4 animate-spin" /> : idx + 1}
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center justify-between">
                        <span className="text-sm font-medium">{step.label}</span>
                        {done && publishUrl && idx === publishSteps.length - 1 && (
                          <a
                            href={publishUrl}
                            target="_blank"
                            rel="noreferrer"
                            className="text-sm text-primary underline"
                          >
                            {publishUrl}
                          </a>
                        )}
                      </div>
                      {active && (
                        <div className="h-1 mt-2 rounded-full bg-muted overflow-hidden">
                          <div className="h-full w-1/2 bg-foreground animate-[progress_1s_infinite]" />
                        </div>
                      )}
                    </div>
                  </div>
                )
              })}
            </div>

            {publishStatus !== "success" && (
              <div className="flex items-center justify-end pt-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => {
                    setIsPublishing(false)
                    setPublishStatus("idle")
                    setPublishStep(0)
                  }}
                  disabled={isPublishing}
                >
                  Cancel
                </Button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}


